version: "3.8"
networks:
  app-net:
    driver: bridge
    name: app-net

services:
  app:
    container_name: "template-api"
    image: template-api
    environment:
      - MAVEN_PROFILE=prod
    networks:
      - app-net
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_PROFILE=${MAVEN_PROFILE}
    ports:
      - "8090:8090"
    restart: unless-stopped
